<a href="https://colab.research.google.com/github/EzraLouis/Data-Mining/blob/main/Tugas_2_Data_Mining_A11_2021_13215_Ezra_Louis_Frasetyo_Preprocessing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [11]:
dataset = pd.read_csv('Data2.csv')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [12]:
print(X)

[['Realme 8' 2021.0 3632000.0]
 ['Oppo A5S' 2019.0 1130000.0]
 ['Infinix Hot 9' 2020.0 1998000.0]
 ['Google Pixel 4a' 2020.0 7674000.0]
 ['Huawei Y5' 2019.0 1525000.0]
 ['Asus Zenfone 7' nan nan]
 ['Xiaomi Redmi Note 12 Pro+' nan nan]
 ['Samsung Galaxy A13' 2022.0 nan]
 ['Apple iPhone 13 Pro Max' nan 16999000.0]
 ['vivo V25 Pro' nan 7499000.0]]


In [13]:
print(Y)

['Yes' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes']


In [14]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3]=imputer.transform(X[:, 1:3])

In [15]:
print(X)

[['Realme 8' 2021.0 3632000.0]
 ['Oppo A5S' 2019.0 1130000.0]
 ['Infinix Hot 9' 2020.0 1998000.0]
 ['Google Pixel 4a' 2020.0 7674000.0]
 ['Huawei Y5' 2019.0 1525000.0]
 ['Asus Zenfone 7' 2020.1666666666667 5779571.428571428]
 ['Xiaomi Redmi Note 12 Pro+' 2020.1666666666667 5779571.428571428]
 ['Samsung Galaxy A13' 2022.0 5779571.428571428]
 ['Apple iPhone 13 Pro Max' 2020.1666666666667 16999000.0]
 ['vivo V25 Pro' 2020.1666666666667 7499000.0]]


In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [17]:
print(X)

  (0, 6)	1.0
  (0, 10)	2021.0
  (0, 11)	3632000.0
  (1, 5)	1.0
  (1, 10)	2019.0
  (1, 11)	1130000.0
  (2, 4)	1.0
  (2, 10)	2020.0
  (2, 11)	1998000.0
  (3, 2)	1.0
  (3, 10)	2020.0
  (3, 11)	7674000.0
  (4, 3)	1.0
  (4, 10)	2019.0
  (4, 11)	1525000.0
  (5, 1)	1.0
  (5, 10)	2020.1666666666667
  (5, 11)	5779571.428571428
  (6, 8)	1.0
  (6, 10)	2020.1666666666667
  (6, 11)	5779571.428571428
  (7, 7)	1.0
  (7, 10)	2022.0
  (7, 11)	5779571.428571428
  (8, 0)	1.0
  (8, 10)	2020.1666666666667
  (8, 11)	16999000.0
  (9, 9)	1.0
  (9, 10)	2020.1666666666667
  (9, 11)	7499000.0


In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [19]:
print(Y)

[1 0 0 0 0 1 1 1 1 1]


In [52]:
from sklearn.model_selection import train_test_split
Y_train, Y_test = train_test_split(Y, shuffle=False)

In [54]:
print(Y_train)

[1 0 0 0 0 1 1]


In [55]:
print(Y_test)

[1 1 1]
